language: python
python:
- '3.7'
install:
- pip install -r dev-requirements.txt
script:
- make -C . clean html
- mv docs/html/* docs/
- touch docs/.nojekyll
deploy:
  - provider: pages:git
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./docs/
    keep_history: true
